#!/bin/sh

CXREPOURL="http://localhost:8081/repository/maven-snapshots"

function command_help() {
	echo "Maven Commands"
	echo "  deploy-to-cxrepo: Deployment into the CX repository ${CXREPOURL}"
	echo "  set-version <version>: set project to <version>"
	echo "  release-prepare <release-version> <new-snapshot-version>"
}

function deploy_to_cxrepo() {
	mvn clean compile install deploy -DaltDeploymentRepository="nexus::default::${CXREPOURL}"
}

function set_version() {
	if [ "$1" == "" ]; then
	  echo "set-version: new version missing"
	else
	  mvn versions:set -DnewVersion="$1"
	  echo "If the update succeeded commit the version with 'versions-commit'"
	fi
}

function release_prepare() {
	if [ "$1" == "" -o "$2" == "" ]; then
	  echo "release-prepare: release-version or new-snapshot-version missing"
	else
		mvn release:prepare -DautoVersionSubmodules=true \
			-DpushChanges=true \
			-DreleaseVersion="$1" \
			-DdevelopmentVersion="$2" \
			-DupdateWorkingCopyVersions=true
	fi
}

function version_commit() {
	mvn versions:commit
}

case "$1" in
	set-version) set_version "$2";;
	versions-commit) version_commit;;
	deploy-to-cxrepo) deploy_to_cxrepo;;
	release-prepare) release_prepare "$2" "$3";;
	help) command_help;;
	*) command_help;;
esac
