name: Wonder Master Build
on: 
  push:
    branches: [cx-dev]
    tags-ignore:
      - wonder-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Wonder Source Code
      uses: actions/checkout@v1

    - name: Cache Maven Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2 # maven dependencies are stored in `~/.m2` on Linux
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Set up Toolchain
      shell: bash
      run: |
          cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
                <provides>
                  <version>8</version>
                  <vendor>adopt</vendor>
                </provides>
                <configuration>
                  <jdkHome>${{ env.TOOLCHAIN_JDK }}</jdkHome>
                </configuration>
            </toolchain>
          </toolchains>
          EOF
    
    - name: Test install Snapshots with Maven
      run: mvn -B install --file pom.xml -s .maven_settings.xml -DretryFailedDeploymentCount=10
