name: Wonder Pull Request Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Wonder Source Code
      uses: actions/checkout@v1

    - name: Cache Maven Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2 # maven dependencies are stored in `~/.m2` on Linux
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up Java 21
      id: setup-java-21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Set up Toolchain
      shell: bash
      run: |
          cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
                <provides>
                  <version>21</version>
                  <vendor>adopt</vendor>
                </provides>
                <configuration>
                  <jdkHome>${{ env.JAVA_HOME }}</jdkHome>
                </configuration>
            </toolchain>
          </toolchains>
          EOF

    - name: Build and Test with Maven
      run: mvn -B package --file pom.xml -s .maven_settings.xml -DretryFailedDeploymentCount=10
